# Generated by Django 3.2.1 on 2021-07-10 21:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('site', models.CharField(default=True, max_length=200, primary_key=True, serialize=False)),
                ('wallet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=200, null=True)),
                ('lname', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('passport', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='passport')),
                ('balance', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.CharField(blank=True, max_length=200, null=True)),
                ('bonus', models.CharField(blank=True, max_length=200, null=True)),
                ('ref', models.CharField(blank=True, max_length=200, null=True)),
                ('msg_head', models.CharField(blank=True, max_length=200, null=True)),
                ('msg_body', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
