# Generated by Django 3.2.1 on 2021-07-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
