# Generated by Django 3.2.1 on 2021-07-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0004_auto_20210711_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
