# Generated by Django 3.2.1 on 2021-07-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0007_auto_20210711_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=200, null=True),
        ),
    ]
