# Generated by Django 3.2.1 on 2021-07-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0008_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='int_bal',
            field=models.CharField(blank=True, default=0.0, max_length=200, null=True),
        ),
    ]
