# Generated by Django 3.2.1 on 2021-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0009_member_int_bal'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='coupon_code',
            field=models.CharField(blank=True, default='4321', max_length=200, null=True),
        ),
    ]
