# Generated by Django 3.2.1 on 2022-09-28 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0012_auto_20220927_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('amt', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 20, 58, 12, 225603), null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('amt', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 20, 58, 12, 225603), null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AlterField(
            model_name='member',
            name='cur',
            field=models.CharField(blank=True, default='€', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
