# Generated by Django 3.2.1 on 2022-09-28 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0014_auto_20220927_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistory',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 21, 30, 56, 609731), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 21, 30, 56, 609731), null=True),
        ),
    ]
