# Generated by Django 3.2.1 on 2022-09-28 06:25

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0015_auto_20220927_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_b',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='id_b'),
        ),
        migrations.AddField(
            model_name='member',
            name='id_f',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='id_f'),
        ),
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 23, 25, 55, 53428), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 27, 23, 25, 55, 53428), null=True),
        ),
    ]
