# Generated by Django 3.2.1 on 2022-09-28 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0016_auto_20220927_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 0, 28, 22, 679888), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 0, 28, 22, 680888), null=True),
        ),
    ]
