# Generated by Django 3.2.1 on 2022-09-28 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0017_auto_20220928_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='verify',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 0, 46, 44, 469552), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 0, 46, 44, 470549), null=True),
        ),
    ]
