# Generated by Django 3.2.1 on 2022-09-28 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0018_auto_20220928_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='subs',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('depo', models.CharField(blank=True, max_length=200, null=True)),
                ('withs', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 3, 33, 22, 433982), null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='msg_body',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 3, 33, 22, 433982), null=True),
        ),
    ]
