# Generated by Django 3.2.1 on 2022-09-28 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0019_auto_20220928_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='subs',
            name='list',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 4, 11, 49, 946821), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 4, 11, 49, 946821), null=True),
        ),
    ]
