# Generated by Django 3.2.1 on 2022-09-28 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0020_auto_20220928_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='plan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 4, 21, 37, 461132), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 28, 4, 21, 37, 461132), null=True),
        ),
    ]
