# Generated by Django 4.1.3 on 2023-02-21 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0021_auto_20220928_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 20, 17, 24, 601409), null=True),
        ),
        migrations.AlterField(
            model_name='subs',
            name='list',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 20, 17, 24, 601409), null=True),
        ),
    ]
