# Generated by Django 4.1.3 on 2023-02-21 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0022_alter_dhistory_date_alter_subs_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 20, 18, 43, 516655), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 20, 20, 18, 43, 516655), null=True),
        ),
    ]
