# Generated by Django 4.1.3 on 2023-03-19 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0023_alter_dhistory_date_alter_whistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 18, 23, 21, 18, 464578), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 18, 23, 21, 18, 465628), null=True),
        ),
    ]
