# Generated by Django 4.1.3 on 2023-03-19 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitfapp', '0024_alter_dhistory_date_alter_whistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 19, 4, 40, 1, 920421), null=True),
        ),
        migrations.AlterField(
            model_name='whistory',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 19, 4, 40, 1, 920421), null=True),
        ),
    ]
